services:
  - type: web
    name: visapath-eoir-scraper
    runtime: node
    buildCommand: apt-get install -y chromium && npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: CAPTCHA_API_KEY
        sync: false
